name: Release Charm

on:
  push:
    branches:
      - main
      - track/**
    paths-ignore:
      - ".github/renovate*"
      - ".github/workflows/release.yaml"
      - ".github/workflows/renovate.yaml"
      - ".github/workflows/update-libs.yaml"
      - ".gitignore"

jobs:
  release:
    uses: canonical/observability/.github/workflows/charm-release.yaml@f1858b296d868435725d617af6f42af7350ba061 # v1
    secrets: inherit
    with:
      provider: machine
      default-track: dev

